apiVersion: v1
kind: Service
metadata:
  name: trip-service
  labels:
    app: trip-service
spec:
  type: ClusterIP
  selector:
    app: trip-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084